spring.application.name=preval
spring.profiles.active=dev

swift.base-url=https://sandbox.swift.com
swift.endpoint=${swift.base-url}/swift-preval/v2


spring.ssl.bundle.jks.channel.key.alias=channel
spring.ssl.bundle.jks.channel.key.password=Abcd1234
spring.ssl.bundle.jks.channel.keystore.location=classpath:sandbox_keystore.jks
spring.ssl.bundle.jks.channel.keystore.password=Abcd1234
spring.ssl.bundle.jks.channel.keystore.type=JKS


spring.security.oauth2.client.registration.swift.client-id=2ZovhB4wZUQsmMcbhbAsOkFADZ29XudS
spring.security.oauth2.client.registration.swift.client-secret=8UqGtXkFrlFSgcby
spring.security.oauth2.client.registration.swift.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.swift.authorization-grant-type=urn:ietf:params:oauth:grant-type:jwt-bearer
spring.security.oauth2.client.registration.swift.scope=swift.preval!p
spring.security.oauth2.client.provider.swift.token-uri=${swift.base-url}/oauth2/v1/token

spring.security.user.name=admin
spring.security.user.password=admin